.PHONY: clean All

All:
	@echo "----------Building project:[ PleaseWork - Debug ]----------"
	@cd "PleaseWork" && "$(MAKE)" -f  "PleaseWork.mk"
clean:
	@echo "----------Cleaning project:[ PleaseWork - Debug ]----------"
	@cd "PleaseWork" && "$(MAKE)" -f  "PleaseWork.mk" clean
