.PHONY: clean All

All:
	@echo "----------Building project:[ Homework_2 - Debug ]----------"
	@cd "Homework_2" && "$(MAKE)" -f  "Homework_2.mk"
clean:
	@echo "----------Cleaning project:[ Homework_2 - Debug ]----------"
	@cd "Homework_2" && "$(MAKE)" -f  "Homework_2.mk" clean
